port: "8080"
releaseMode: "False" # True or False
url_parse_data: "localhost:8001/api/parse/data"

db:
  host: "localhost"
  port: "5436"
  username: "admin"
  dbname: "freelancer"
  sslmode: "disable"